# -*- coding: utf-8 -*-
"""SENet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T-79A8nnW3XACI_5QZc-vFtkSnY8ud42
"""

class SEblock(nn.Module):
    def __init__(self, in_channels, reduction=16):
        super(SEblock, self).__init__()
        self.squeeze_avg = nn.AdaptiveAvgPool2d(1)
        self.excitation = nn.Sequential(
            nn.Linear(in_channels, in_channels // reduction, bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(in_channels // reduction, in_channels, bias=False),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.squeeze_avg(x)
        x = x.view(x.size(0), -1)  # dimension 1x1 -> 1
        x = self.excitation(x)

        return x